version = 1
SPDX-PackageName = "frun-csa-policies-best-practices"
SPDX-PackageSupplier = "Manfred Ach <manfred.ach@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/SAP-samples/frun-csa-policies-best-practices"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2020 SAP SE or an SAP affiliate company and frun-csa-policies-best-practices"
SPDX-License-Identifier = "Apache-2.0"
